### ISSUE TITLE
perlreref: wording

### ISSUE THREAD

**Issue by zoffixznet** [mishin/POD-to-RU#3]
I think the wording in this sentence should be modified:

```
Наконец, разделители по умолчанию // для поиска могут быть изменены на произвольные разделители, но тогда в начале должны быть буква 'm':
```

I don't have a Russian keyboard handy, but it should read the same as in English version: letter `m` can be omited if delimiters are `//`, not that it's required when delimiters are arbitrary.

The distinction is subtle, but it's significant because some delimiters require not only `m` alone, but also a space between `m` and the delimiter itself.

Consider these two examples:

```
zoffix@~:~$ perl -E 'say "foo" =~ m{foo} ? "y" : "n"'
y
zoffix@~:~$ perl -E 'say "foo" =~ m mfoom ? "y" : "n"'
y
```

The second version requires a space between `m` and the delimiter. The Russian translation of the document implies the second version should be `mmfoom`.

**Comment by mishin** [comment]
Waw, It's my first issue, thanks a lot!

**Comment by mishin** [comment]
спасибо, верное замечание, 
thanks for this bug,
when I found time - i fix it

**Comment by mishin** [comment]
исправил, zoffixznet++
