### ISSUE TITLE
Новый релиз с подправленным линком

### ISSUE THREAD

**Issue by ribasushi** [mishin/POD-to-RU#5]
Николай,

Давайте залейте на CPAN дистрибутивчик? Сегодня идет народ на https://metacpan.org/release/MISHIN/POD2-RU-5.18.0.1.82, кликает "красную кнопку" и попадает в пустую комнату `#moscowpm`.

В `#ru.pm` нас хоть и мало, но по крайней мере не пусто...

**Comment by asan13** [comment]
+1

**Comment by mishin** [comment]
хорошо, согласен, сейчас залью!! (дайте пару дней..хотя может и быстрее)

**Comment by mishin** [comment]
Сделано, спасибо, что толкнули меня;-)
https://metacpan.org/release/MISHIN/POD2-RU-5.18.0.1.83
